### ISSUE TITLE
RPi3 setup and execution

### ISSUE THREAD

**Issue by aben20807** [YI-LING-BA-JI-JHUAN-TI-SHENG/project#3]
###### master setup
`$ sudo vim /etc/hosts`
set master ip
`xxx.xxx.xxx.xxx master`

###### execution
`$ ssh ubuntu@192.168.1.108`
`$ rosrun uvc_camera uvc_camera_node`

**Comment by F74046080** [comment]
https://github.com/YI-LING-BA-JI-JHUAN-TI-SHENG/documents/commit/b944b53b6f1df57365c958d4c98dbbf3184de2e9
